server:
  port: 8080

spring:
  application:
    name: rabbitmq-broadcasting-service-a
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 1
        prefetch: 10
